/**
 * Font package: newsreaderFonts
 * Generated by scripts/generate-font-package/generate-font-package.py — edit as needed.
 *
 * Values are PostScript names — works on both iOS and Android.
 * Italic keys use the weight suffixed with 'i' (e.g. '400i', '700i').
 */

export type TFontWeightToken = '200' | '300' | '400' | '500' | '600' | '700' | '800' | '200i' | '300i' | '400i' | '500i' | '600i' | '700i' | '800i';
export type TFontFamilyMap = Partial<Record<TFontWeightToken, string>>;
export type TFontPackage = Record<string, TFontFamilyMap>;

export const newsreaderFonts: TFontPackage = {
  newsreader14pt: {
    '200': 'Newsreader14pt-ExtraLight',
    '300': 'Newsreader14pt-Light',
    '400': 'Newsreader14pt-Regular',
    '500': 'Newsreader14pt-Medium',
    '600': 'Newsreader14pt-SemiBold',
    '700': 'Newsreader14pt-Bold',
    '800': 'Newsreader14pt-ExtraBold',
    '200i': 'Newsreader14pt-ExtraLightItalic',
    '300i': 'Newsreader14pt-LightItalic',
    '400i': 'Newsreader14pt-Italic',
    '500i': 'Newsreader14pt-MediumItalic',
    '600i': 'Newsreader14pt-SemiBoldItalic',
    '700i': 'Newsreader14pt-BoldItalic',
    '800i': 'Newsreader14pt-ExtraBoldItalic',
  },
  newsreader24pt: {
    '200': 'Newsreader24pt-ExtraLight',
    '300': 'Newsreader24pt-Light',
    '400': 'Newsreader24pt-Regular',
    '500': 'Newsreader24pt-Medium',
    '600': 'Newsreader24pt-SemiBold',
    '700': 'Newsreader24pt-Bold',
    '800': 'Newsreader24pt-ExtraBold',
    '200i': 'Newsreader24pt-ExtraLightItalic',
    '300i': 'Newsreader24pt-LightItalic',
    '400i': 'Newsreader24pt-Italic',
    '500i': 'Newsreader24pt-MediumItalic',
    '600i': 'Newsreader24pt-SemiBoldItalic',
    '700i': 'Newsreader24pt-BoldItalic',
    '800i': 'Newsreader24pt-ExtraBoldItalic',
  },
  newsreader36pt: {
    '200': 'Newsreader36pt-ExtraLight',
    '300': 'Newsreader36pt-Light',
    '400': 'Newsreader36pt-Regular',
    '500': 'Newsreader36pt-Medium',
    '600': 'Newsreader36pt-SemiBold',
    '700': 'Newsreader36pt-Bold',
    '800': 'Newsreader36pt-ExtraBold',
    '200i': 'Newsreader36pt-ExtraLightItalic',
    '300i': 'Newsreader36pt-LightItalic',
    '400i': 'Newsreader36pt-Italic',
    '500i': 'Newsreader36pt-MediumItalic',
    '600i': 'Newsreader36pt-SemiBoldItalic',
    '700i': 'Newsreader36pt-BoldItalic',
    '800i': 'Newsreader36pt-ExtraBoldItalic',
  },
  newsreader60pt: {
    '200': 'Newsreader60pt-ExtraLight',
    '300': 'Newsreader60pt-Light',
    '400': 'Newsreader60pt-Regular',
    '500': 'Newsreader60pt-Medium',
    '600': 'Newsreader60pt-SemiBold',
    '700': 'Newsreader60pt-Bold',
    '800': 'Newsreader60pt-ExtraBold',
    '200i': 'Newsreader60pt-ExtraLightItalic',
    '300i': 'Newsreader60pt-LightItalic',
    '400i': 'Newsreader60pt-Italic',
    '500i': 'Newsreader60pt-MediumItalic',
    '600i': 'Newsreader60pt-SemiBoldItalic',
    '700i': 'Newsreader60pt-BoldItalic',
    '800i': 'Newsreader60pt-ExtraBoldItalic',
  },
  newsreader9pt: {
    '200': 'Newsreader9pt-ExtraLight',
    '300': 'Newsreader9pt-Light',
    '400': 'Newsreader9pt-Regular',
    '500': 'Newsreader9pt-Medium',
    '600': 'Newsreader9pt-SemiBold',
    '700': 'Newsreader9pt-Bold',
    '800': 'Newsreader9pt-ExtraBold',
    '200i': 'Newsreader9pt-ExtraLightItalic',
    '300i': 'Newsreader9pt-LightItalic',
    '400i': 'Newsreader9pt-Italic',
    '500i': 'Newsreader9pt-MediumItalic',
    '600i': 'Newsreader9pt-SemiBoldItalic',
    '700i': 'Newsreader9pt-BoldItalic',
    '800i': 'Newsreader9pt-ExtraBoldItalic',
  },
};
