/**
 * Font package: newsreaderFonts
 * Generated by scripts/generate-font-package/generate-font-package.py — edit as needed.
 *
 * Values are PostScript names — works on both iOS and Android.
 */

export type TFontWeightToken = '200' | '300' | '400' | '500' | '600' | '700' | '800';
export type TFontFamilyMap = Record<TFontWeightToken, string>;
export type TFontPackage = Record<string, TFontFamilyMap>;

export const newsreaderFonts: TFontPackage = {
  newsreader14pt: {
    '200': 'Newsreader14pt-ExtraLight',
    '300': 'Newsreader14pt-Light',
    '400': 'Newsreader14pt-Regular',
    '500': 'Newsreader14pt-Medium',
    '600': 'Newsreader14pt-SemiBold',
    '700': 'Newsreader14pt-Bold',
    '800': 'Newsreader14pt-ExtraBold',
  },
  newsreader24pt: {
    '200': 'Newsreader24pt-ExtraLight',
    '300': 'Newsreader24pt-Light',
    '400': 'Newsreader24pt-Regular',
    '500': 'Newsreader24pt-Medium',
    '600': 'Newsreader24pt-SemiBold',
    '700': 'Newsreader24pt-Bold',
    '800': 'Newsreader24pt-ExtraBold',
  },
  newsreader36pt: {
    '200': 'Newsreader36pt-ExtraLight',
    '300': 'Newsreader36pt-Light',
    '400': 'Newsreader36pt-Regular',
    '500': 'Newsreader36pt-Medium',
    '600': 'Newsreader36pt-SemiBold',
    '700': 'Newsreader36pt-Bold',
    '800': 'Newsreader36pt-ExtraBold',
  },
  newsreader60pt: {
    '200': 'Newsreader60pt-ExtraLight',
    '300': 'Newsreader60pt-Light',
    '400': 'Newsreader60pt-Regular',
    '500': 'Newsreader60pt-Medium',
    '600': 'Newsreader60pt-SemiBold',
    '700': 'Newsreader60pt-Bold',
    '800': 'Newsreader60pt-ExtraBold',
  },
  newsreader9pt: {
    '200': 'Newsreader9pt-ExtraLight',
    '300': 'Newsreader9pt-Light',
    '400': 'Newsreader9pt-Regular',
    '500': 'Newsreader9pt-Medium',
    '600': 'Newsreader9pt-SemiBold',
    '700': 'Newsreader9pt-Bold',
    '800': 'Newsreader9pt-ExtraBold',
  },
};
